theme: jekyll-theme-minimal
title: Mansa Krishna
description: B.S. Applied Mathematics with Specialization in Computing, University of California, Los Angeles (UCLA). Incoming doctoral student at Dartmouth for the Earth Sciences.
logo: /img/mansa.png
