theme: jekyll-theme-minimal
title: 
description: An undergraduate student pursuing Applied Mathematics with a Specialization in Computing at the University of California, Los Angeles (UCLA). Currently an undergraduate researcher with the Pablo Saide Research Group at UCLA and intend to pursue graduate studies in the Earth Sciences. My primary research interests include applications of Machine Learning and Numerical Methods to the Earth Sciences.
logo: /img/mansa.png
