theme: jekyll-theme-minimal
title: Mansa Krishna
author: Curriculum Vitae

navbar-links:
  LinkedIn: "https://www.linkedin.com/in/mansa-krishna-96682419b"
  GitHub: "https://github.com/mansakrishna23"
  Blog: "https://mansakrishna23.github.io/"

avatar: "/img/mansa.png"
round-avatar: true
