theme: jekyll-theme-minimal
title: Mansa Krishna
description: PhD Candidate, Earth Sciences, Dartmouth | B.S. Applied Mathematics, Specialization in Computing, University of California, Los Angeles (UCLA). 
logo: /img/Mansa.jpeg
