theme: jekyll-theme-minimal
title: Mansa Krishna
description: An undergraduate student pursuing Applied Mathematics with a Specialization in Computing at the University of California, Los Angeles (UCLA).
logo: /img/mansa.png
