theme: jekyll-theme-minimal
title: Mansa Krishna
description: I am an undergraduate student pursuing a bachelors degree in Applied Mathematics with a specialization in Computing at the University of California, Los Angeles (UCLA). I am currently an undergraduate researcher with the Pablo Saide Research Group at UCLA and intend to pursue graduate studies in the Earth Sciences. My primary research interests include applications of Machine Learning and Numerical Methods to the Earth Sciences.
photo: img/mansa.png
